### ISSUE TITLE
1B model validation

### ISSUE THREAD

**Issue by vickitoy** [DataKind-DC/red-cross-2#20]

**Comment by vickitoy** [comment]
Discrepancy between replication files and old files:

For files 'tract_data_weighted_linear_preds_upsampled.csv' and 'tract_data_weighted_linear_preds_upsampled_REPLICATION.csv' discrepancy:

column_name, percentage_mismatched
all_fire_all_years,0.0
alarm_unknown_all_years, 0.0
alarm_presented_all_years, 0.0
alarm_not_presented_all_years, 0.0
ratio_no_alarm_in_all, 0.476121924348
ratio_no_alarm_in_all_known, 0.417319133309
weighted_linear_pred, 1.0

**Comment by vickitoy** [comment]
Discrepancy between original ('tract_data_weighted_linear_preds_upsampled.csv') and replication file ('tract_data_weighted_linear_preds_upsampled_REPLICATION.csv' 

Where mismatched means the absolute value of the difference is greater than 0.01

column_name, percentage_mismatched
all_fire_all_years, 0.0
alarm_unknown_all_years, 0.0
alarm_presented_all_years, 0.0
alarm_not_presented_all_years, 0.0
ratio_no_alarm_in_all, 0.0
ratio_no_alarm_in_all_known, 0.0
weighted_linear_pred, 0.936437752479

**Comment by vickitoy** [comment]
Replication - Old weighted_linear_pred

![replication_difference](https://user-images.githubusercontent.com/5963932/40948930-4e9d36d4-6839-11e8-849e-c9959ffae4d5.png)

**Comment by maria-brun** [comment]
The weird part about this model is that on the GitHub, there were originally 4 output files. The one actually used is the 74k upsampled. The results of this file are nearly dead on. The rest are not even close.

**Comment by maria-brun** [comment]
See this document https://github.com/DataKind-DC/red-cross-2/blob/master/Model-1B/Model%201B%20Replication%20Documentation.md
